app:
    name: exchane-chain
    version: 2.0-RELEASE
server:
  port: 18080
ribbon:
    ReadTimeout: 120000
    ConnectTimeout: 60000
spring:
  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
#      =======online=======
#      url: jdbc:mysql://127.0.0.1:3306/exchange-chain?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
#      password:12345
#    ========test=======
      url: jdbc:mysql://127.0.0.1:3306/exchange-chain?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false
      password: 123456
      username: xxx
      initial-size: 5
      min-idle: 5
      max-active: 30
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  redis:
#  ========online========
#    host: 127.0.0.1
#  ========test========
    host: 127.0.0.1
    password: 123456
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 200
        max-wait: 1
        max-idle: 10
        min-idle: 0
        timeout: 1000
  application:
    name: coinstudy-api-invoker
mybatis:
  mapper-locations: classpath*:mapper/**Mapper.xml
  type-aliases-package: com.fuxi.entity

pagehelper:
  auto-dialect: mysql
  reasonable: true
  support-methods-arguments: ture
  params: count=countSql
  returnPageInfo: check

#日志
logging:
  level:
    com:
      coinstudy:
                 dao: debug
eureka:
  instance:
    hostname: localhost
#    instance-id: ${spring.application.name}
#    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #,http://localhost:8762/eureka/
    registry-fetch-interval-seconds: 30
#    healthcheck: true
#
feign:
  hystrix:
    enabled: false
#The third party sms supplier config
sms:
      driver: two_five_three
      gateway: http://smssh1.253.com/msg/send/json
      username: xxxxx
      password: xxxx
      sign: xxxx