app:
    name: exchane-registration
    version: 1.0-RELEASE
server:
  port: 8761
spring:
  application:
    name: registration-server
    profiles: server-no1
  profiles:
    active: server-no1
#    active: server-no2
eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: server-no1
#    关闭自我保护
  server:
    enable-self-preservation: false
---
#server:
#  port: 8762
#spring:
#  application:
#    name: registration-server
#  profiles: server-no2
#eureka:
#  client:
#    healthcheck: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    fetch-registry: true
#    register-with-eureka: true
#  instance:
#     hostname: server-no2
#     关闭自我保护
#  server:
#    enable-self-preservation: false
