server:
  port: 18082

encrypt-type: # 0：普通， 1：国密
  encrypt-type: 0

group-channel-connections-config:
  caCert: classpath:/ca.crt
  sslCert: classpath:/sdk.crt
  sslKey: classpath:/sdk.key
  all-channel-connections:
    - group-id: 1 #group ID
      connections-str:
        # 若节点小于v2.3.0版本，查看配置项listen_ip:channel_listen_port
        - 127.0.0.1:20200 # node channel_listen_ip:channel_listen_port
        - 127.0.0.1:20201
    - group-id: 2
      connections-str:
        # 若节点小于v2.3.0版本，查看配置项listen_ip:channel_listen_port
        - 127.0.0.1:20202 # node channel_listen_ip:channel_listen_port
        - 127.0.0.1:20203
channel-service:
  group-id: 1 # sdk实际连接的群组
  agency-name: fisco   # 机构名称
spring:
  redis:
    host: 127.0.0.1
    password: 123456
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 200
        max-wait: 1
        max-idle: 10
        min-idle: 0
        timeout: 1000
  application:
           name: exchange-bridge
  datasource:
      name: mysql_test
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        filters: stat
        driver-class-name: com.mysql.jdbc.Driver
  #      =======online=======
  #      url: jdbc:mysql://127.0.0.1:3306/exchange-chain?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
  #      password: 123456
  #    =======test=======
        url: jdbc:mysql://127.0.0.1:3306/exchange-bridge-chain?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false
        password: 123456!
        username: root
        initial-size: 5
        min-idle: 5
        max-active: 30
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 'x'
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: false
        max-pool-prepared-statement-per-connection-size: 20
mybatis:
  mapper-locations: classpath*:mapper/**Mapper.xml
  type-aliases-package: com.fuxi.bridge.entity

pagehelper:
  auto-dialect: mysql
  reasonable: true
  support-methods-arguments: ture
  params: count=countSql
  returnPageInfo: check

#logs
event-log:
        tranferEvent:
              fromBlock: 1

ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
#      eureka config
eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/ #,http://localhost:8762/eureka/

#contracts config
contracts:
        StorageController:
                          address: "0x13d8b8906b2fc56aa2c829487b87ae4e60488358"
        ScoreDB:
                          address: "0x1635646c4221f696b06233f9a3e124ef2c577377"
# contracts owner private key primary id in mysql
admin:
        keypairs:
                id: 18
logging:
  level:
      com:
          fuxi:
              bridge:
                    dao: debug
