#===========业务内配置文件==============
app:
    name: exchange-chain-uc
    version: 2.0-RELEASE
server:
  port: 18081
ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
spring:
  application:
    name: customer-center-exchange
  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
#      =======online=======
#      url: jdbc:mysql://127.0.0.1:3306/coin_study?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
#      password: 123456
#    =======test=========
      url: jdbc:mysql://127.0.0.1:3306/exchange-chain?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false
      password: 123456
      username: root
      initial-size: 5
      min-idle: 5
      max-active: 30
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  redis:
#     ========online========
#    host: 127.0.0.01
#     ========test========
    host: 127.0.0.1
    password: 123456
    port: 6379
    database: 0
    jedis:
          pool:
            max-active: 200
            max-wait: 1
            max-idle: 10
            min-idle: 0
            timeout: 1000
mybatis:
  mapper-locations: classpath*:mapper/**Mapper.xml
  type-aliases-package: com.fuxi.entity

#pagehelper
pagehelper:
  auto-dialect: mysql
  reasonable: true
  support-methods-arguments: ture
  params: count=countSql
  returnPageInfo: check

#logs
logging:
  level:
    com:
      coinstudy:
                 dao: debug
#      eureka配置
eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/ #,http://localhost:8762/eureka/
